# -*- coding: utf-8 -*-
"""лаба 6

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FoeIT9cX-1ks5CbPTsGbCrX59WhNhJ7D

Задание 1
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression


fahrenheit = [[-88.6], [-29.2], [32.0], [93.2], [129.2], [152.6], [212.0]]


kelvin = (np.array(fahrenheit) - 32) * 5/9 + 273.15


plt.figure(figsize=(10, 6), dpi=100)
plt.scatter(fahrenheit, kelvin, label='входные данные', color='green', marker='$f$')
plt.xlabel('Fahrenheit')
plt.ylabel('Kelvin')
plt.legend()
plt.grid(True)
plt.show()


lr = LinearRegression()
lr.fit(fahrenheit, kelvin)

print('coef_ =', lr.coef_)
print('intercept_ =', lr.intercept_)


f_test = [[-58.0], [32.0], [212.0]]
k_pred = lr.predict(f_test)

for f, k in zip(f_test, k_pred):
    print(f'Фаренгейт {f} = Кельвин {k}')


x_range = np.arange(-100, 250)
y_range = (x_range - 32) * 5/9 + 273.15

plt.figure(figsize=(12, 6), dpi=100)
plt.plot(x_range, y_range, label='уравнение', linewidth='1', color='orange')
plt.scatter(fahrenheit, kelvin, label='обучающие данные', color='green')
plt.scatter(f_test, k_pred, label='предсказанные значения', color='blue')
plt.xlabel('Фаренгейт')
plt.ylabel('Кельвин')
plt.legend()
plt.grid(True)
plt.show()

"""Задание 2"""

!git clone https://github.com/MuradKuriev/KurievMG_PI-311.git

"""Задание 3"""

import matplotlib.pyplot as plt


names = ['A', 'B', 'C', 'D', 'E']
values = [10, 24, 36, 15, 5]


plt.figure(figsize=(8, 4))
plt.bar(names, values, color='purple')
plt.title('Столбчатая диаграмма')
plt.show()


plt.figure(figsize=(6, 6))
plt.pie(values, labels=names, autopct='%1.1f%%')
plt.title('Круговая диаграмма')
plt.show()


plt.figure(figsize=(8, 4))
plt.stem(names, values)
plt.title('Stem Plot')
plt.show()

"""Задание 4"""

import math

print(f"Число Эйлера (e): {math.e}")


print(f"Число Пи (pi): {math.pi}")


print(f"Значение nan: {math.nan}")


my_number = 11
print(f"Факториал числа {my_number}: {math.factorial(my_number)}")


phone_mem = 256000
print(f"НОД числа {my_number} и {phone_mem}: {math.gcd(my_number, phone_mem)}")

"""Повышенная сложность

Задание 1
"""

import matplotlib.pyplot as plt


head_x = [1, 1, 2, 2.5, 3, 3.5, 4, 5, 5, 4.5, 4, 3, 2, 1]
head_y = [5, 7, 8, 7.5, 8, 7.5, 8, 7, 5, 4, 4, 4, 4, 5]


l_ear_x = [1, 0.5, 2]
l_ear_y = [7, 9, 8]
r_ear_x = [4, 5.5, 5]
r_ear_y = [8, 9, 7]


eye_l_x = [2]
eye_l_y = [6]
eye_r_x = [4]
eye_r_y = [6]


nose_x = [3]
nose_y = [5]


mouth_x = [3, 3, 2.5, 3.5]
mouth_y = [5, 4.5, 4.5, 4.5]

plt.figure(figsize=(6, 6))


plt.fill(head_x, head_y, color='gray', alpha=0.5, label='Голова')
plt.plot(head_x, head_y, color='black', linewidth=2)

plt.plot(l_ear_x, l_ear_y, color='black', linewidth=2)
plt.plot(r_ear_x, r_ear_y, color='black', linewidth=2)

plt.scatter(eye_l_x, eye_l_y, s=100, c='green', zorder=5)
plt.scatter(eye_r_x, eye_r_y, s=100, c='green', zorder=5)
plt.scatter(nose_x, nose_y, s=50, c='pink', zorder=5)

plt.plot([3, 3], [5, 4.5], color='black')
plt.plot([2.5, 3.5], [4.5, 4.5], color='black')

plt.title('Котик')
plt.axis('equal')
plt.axis('off')
plt.show()

"""Задание 2

"""

import tensorflow as tf
from tensorflow import keras
import numpy as np
import matplotlib.pyplot as plt


print("Загрузка Fashion MNIST...")
fashion_mnist = keras.datasets.fashion_mnist
(train_images, train_labels), (test_images, test_labels) = fashion_mnist.load_data()

class_names = ['Футболка', 'Штаны', 'Пуловер', 'Платье', 'Пальто',
               'Сандалии', 'Рубашка', 'Кроссовки', 'Сумка', 'Ботинки']


train_images = train_images / 255.0
test_images = test_images / 255.0


plt.figure(figsize=(10, 5))
for i in range(10):
    plt.subplot(2, 5, i+1)
    plt.xticks([])
    plt.yticks([])
    plt.grid(False)

    idx = np.where(train_labels == i)[0][0]
    plt.imshow(train_images[idx], cmap=plt.cm.binary)
    plt.xlabel(class_names[i])
plt.show()


model = keras.Sequential([
    keras.layers.Flatten(input_shape=(28, 28)),
    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dense(10, activation='softmax')
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])


print("Начинаем обучение...")
model.fit(train_images, train_labels, epochs=5)


predictions = model.predict(test_images)


def plot_image(i, predictions_array, true_label, img):
  predictions_array, true_label, img = predictions_array, true_label[i], img[i]
  plt.grid(False)
  plt.xticks([])
  plt.yticks([])
  plt.imshow(img, cmap=plt.cm.binary)

  predicted_label = np.argmax(predictions_array)
  color = 'blue' if predicted_label == true_label else 'red'

  plt.xlabel("{} {:2.0f}%".format(class_names[predicted_label],
                                100*np.max(predictions_array)),
                                color=color)


plt.figure(figsize=(10, 3))
for i in range(5):
    plt.subplot(1, 5, i+1)
    plot_image(i, predictions[i], test_labels, test_images)
plt.show()