# -*- coding: utf-8 -*-
"""лаба 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KBJS-nNjuIKJIuKdbM1L7FuldTGAFrKw
"""

# пример 1
print("Hello World")

# пример 2
a = 5
b = 2
c = a + b
print(c)

# пример 3
side = 7.5
h = 6.5  # просто берём высоту для примера
s = side * h / 2
print("Площадь треугольника =", s)

# пример 4
a = 5
b = 3
c = 2
x = (a * a + b * b - c * c * c) / 2
print("x =", x)

"""Самостоятельные задания

"""

# 1
a = 5
b = int(input("Введите b: "))
p = a * b
print(p)

# 2
a = int(input("Введите a: "))
b = int(input("Введите b: "))
s = (a + b) ** 2
print(s)

# 3
a = 15
b = 10
c = float(input("Введите c: "))
r = (a + b) / c
print(r)

# 4
a = float(input("Введите первое число: "))
b = float(input("Введите второе число: "))
res = (a + b) ** 2
print(res)

# 5
a = float(input("Введите сторону a: "))
b = float(input("Введите сторону b: "))
c = float(input("Введите сторону c: "))

p = a + b + c
pol = p / 2
s = (pol * (pol - a) * (pol - b) * (pol - c)) ** 0.5

print("Периметр:", p)
print("Площадь:", s)

# 6
a = float(input("Введите a: "))
b = float(input("Введите b: "))
res = ((a ** 3 + 14) / 5) * b
print(res)

# 7
x = int(input("Введите число: "))
n = int(input("Введите n: "))
res = (x * x) // n
print(res)

# 8
# деление двух дробных чисел без остатка
x1 = float(input("Введите первое дробное: "))
x2 = float(input("Введите второе дробное: "))
d = x1 // x2
print(d)

# умножение двух натуральных
y1 = int(input("Введите первое натуральное: "))
y2 = int(input("Введите второе натуральное: "))
m = y1 * y2
print(m)

# остаток от деления
z1 = int(input("Введите первое натуральное: "))
z2 = int(input("Введите второе натуральное: "))
o = z1 % z2
print(o)

"""Повышенная сложность"""

# 1
n = int(input("Введите секунды: "))

days = n // 86400
hours = (n % 86400) // 3600
mins = (n % 3600) // 60
secs = n % 60

print(days, "дней", hours, "часов", mins, "минут", secs, "секунд")

# 2
n = int(input("Введите n: "))

nn = int(str(n) + str(n))
nnn = int(str(n) + str(n) + str(n))

s = n + nn + nnn
print(s)