# -*- coding: utf-8 -*-
"""лаба 3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cESNi5zgD4-Zmy-Y28UZ9qqVUPSl2FKJ

### 1. Календарь (номер месяца → название)
"""

num = int(input("Введите номер месяца (1-12): "))

if num == 1:
    print("Январь")
elif num == 2:
    print("Февраль")
elif num == 3:
    print("Март")
elif num == 4:
    print("Апрель")
elif num == 5:
    print("Май")
elif num == 6:
    print("Июнь")
elif num == 7:
    print("Июль")
elif num == 8:
    print("Август")
elif num == 9:
    print("Сентябрь")
elif num == 10:
    print("Октябрь")
elif num == 11:
    print("Ноябрь")
elif num == 12:
    print("Декабрь")
else:
    print("Нет такого месяца")

"""2. Чётное / нечётное"""

n = int(input("Введите число: "))

if n % 2 == 0:
    print("Чётное")
else:
    print("Нечётное")

"""3. Stonks / not stonks"""

n = int(input("Введите число N: "))

if n > 40:
    print("stonks")
else:
    print("not stonks")

"""4. Функция is_year_leap (високосный год)"""

def is_year_leap(year):
    if (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0):
        return True
    else:
        return False

y = int(input("Введите год: "))
print(is_year_leap(y))

"""5. Функция is_prime (простое число)

"""

def is_prime(n):
    if n <= 1:
        return False

    i = 2
    while i * i <= n:
        if n % i == 0:
            return False
        i = i + 1

    return True

num = int(input("Введите число: "))
print(is_prime(num))

"""6. Поменять значения местами по условию"""

a = float(input("Введите a: "))
b = float(input("Введите b: "))


left = -100.0
right = 100.0

if a > b * 3.6 or (b >= left and b <= right):
    temp = a
    a = b
    b = temp

print("a =", a)
print("b =", b)

"""7. Пять чисел: уникальность и подсчёты"""

nums = []

nums.append(int(input("Введите число 1: ")))
nums.append(int(input("Введите число 2: ")))
nums.append(int(input("Введите число 3: ")))
nums.append(int(input("Введите число 4: ")))
nums.append(int(input("Введите число 5: ")))

# все ли уникальны
all_unique = True
i = 0
while i < len(nums):
    j = i + 1
    while j < len(nums):
        if nums[i] == nums[j]:
            all_unique = False
        j = j + 1
    i = i + 1

if all_unique:
    print("Все числа уникальные")
else:
    print("Есть одинаковые числа")

# количество чётных
even_count = 0
# количество отрицательных
neg_count = 0
# количество в промежутке [-256; 1024]
range_count = 0

for x in nums:
    if x % 2 == 0:
        even_count = even_count + 1
    if x < 0:
        neg_count = neg_count + 1
    if x >= -256 and x <= 1024:
        range_count = range_count + 1

print("Чётных:", even_count)
print("Отрицательных:", neg_count)
print("В диапазоне [-256; 1024]:", range_count)

"""Задача повышенной сложности"""

a = float(input("Введите a: "))
b = float(input("Введите b: "))
c = float(input("Введите c: "))

res = (a ** 2 + b ** 3) / (c + 3) / 4
print("Результат =", res)

# проверка на чётность для целой части
n = int(res)

if n % 2 == 0:
    print("Целая часть результата чётная")
else:
    print("Целая часть результата нечётная")

